### ISSUE TITLE
Error while building project

### ISSUE THREAD

**Issue by trkfabi** [loop-modules/Ti.Firebase#1]
I'm using Ti SDK: 6.1.1.GA , Hyperloop: 2.1.2, CocoaPod: 1.2.1, Xcode: 8.3.3.
I'm getting this error when building the app.

This is part of the console log (I don't know if it is of any use):
```[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/HL_Firebase, Resource: HL_Firebase
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/HL_Firebase.js, Resource: HL_Firebase_js
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp, Resource: hyperloop/firebaseanalytics/firapp
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp.js, Resource: hyperloop/firebaseanalytics/firapp_js
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp.json, Resource: hyperloop/firebaseanalytics/firapp_json
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp/package.json, Resource: hyperloop/firebaseanalytics/firapp/package_json
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp/index.js, Resource: hyperloop/firebaseanalytics/firapp/index_js
[DEBUG] Loading: /Users/Fabi/Library/Developer/CoreSimulator/Devices/BE891529-DEE3-47C4-A31F-45371BD940B2/data/Containers/Bundle/Application/76E23DAB-D771-4618-B8A5-973AE6202660/Firebase.app/hyperloop/firebaseanalytics/firapp/index.json, Resource: hyperloop/firebaseanalytics/firapp/index_json
[ERROR] Script Error Couldn't find module: /hyperloop/firebaseanalytics/firapp for architecture: x86_64
[ERROR] Script Error Module "HL_Firebase.js" failed to leave a valid exports object
[ERROR] ErrorController is up. ABORTING showing of modal controller
[DEBUG] Application booted in 130.621016 ms
[TRACE] [HYPERLOOP] didStartNewContext <KrollContext: 0x600000e6bdc0>
[TRACE] updating tiapp metadata with Appcelerator Platform...
[TRACE] Uploaded tiapp metadata with Appcelerator Platform!
```

The Pods folder seems to be right:
![image](https://user-images.githubusercontent.com/1564477/27748904-a06d8524-5da7-11e7-8e89-1a68e1d68fc5.png)

![simulator screen shot jun 30 2017 1 50 46 pm](https://user-images.githubusercontent.com/1564477/27748735-e1a4f03c-5da6-11e7-85bb-553de03b7978.png)

**Comment by xicovarisco** [comment]
Hi @trkfabi,
Thanks for submitting an issue on the repo. 
Did you download you GoogleService-Info.plist from Firebase? 
Did you put the file HL_Firebase.js inside a "lib" folder? 

Cheers

**Comment by trkfabi** [comment]
I'm trying to build a cloned version of this git, so HL_Firebase.js is in the lib folder (it was already there).
Yes, I have downloaded the GoogleService-Info.plist from Firebase and replaced this file in the "src" folder.

I haven't modified the code.

Thank you.

**Comment by xicovarisco** [comment]
Hi @trkfabi,

I did the same test and I got the same result as you, so you're right, we do have an issue.
However, I had a look at the Appcelerator's documentation for the new 6.1.1.GA SDK and it looks like the have unveiled Javascript ES6 functionalities. 
They are having some problems with exports on this version as you can see in this ticket: https://jira.appcelerator.org/browse/ALOY-1570?jql=text%20~%20%22exports%22%20ORDER%20BY%20created%20DESC
It looks like the Alloy version that we are running doesn't understand those type of exports and therefore fail on compile the application. 
So, at the end of the day that's not a problem with the Firebase application, but with the environment. 
The last time I got this module to work I as running the SDK version 6.0.1.GA and I bet it would still work on this version.
We might have to wait until Appcelerator decided to ship the new CLI version (6.3.0) with the new Alloy which should fix this issue.
Does it make sense?

Cheers,

Francisco Varisco

**Comment by trkfabi** [comment]
Hi Francisco,

Yeah, looks like you nailed the problem!
Thank you for taking the time to dig into this issue.

Great job with all those Loopmodules projects by the way!

Best,
Fabian

**Comment by trkfabi** [comment]
Hi,

is it possible that Firebase moved FIRApp from FirebaseAnalytics to FirebaseCore ?

Replacing the “requires" lines in HL_Firebase.js seems to work:

var FIRApp = require('FirebaseCore/FIRApp'),
    FIROptions = require('FirebaseCore/FIROptions’);

**Comment by xicovarisco** [comment]
It might be possible @trkfabi. I haven't checked their documentation recently.
Is it working with FirebaseCore?

If it is, can you make a pull request ? 
Cheers

**Comment by anthonychung** [comment]
@trkfabi I can confirm in testing changing FirebaseAnalytics to FirebaseCore works for me too.

**Comment by anthonychung** [comment]
@xicovarisco nice repo for getting to know hyperloop and firebase. thanks.

**Comment by xicovarisco** [comment]
Thanks for the feedback @anthonychung. I have just updated the project. :)

Use the module as much as you can 👍
